EVENTS = {
    "АБОРТ": 1,
    "БОЛЕЗНЬ": 2,
    "ВАКВИРУС": 3,
    "ВАКЦИН": 4,
    "ВЕС": 5,
    "ДЕФЕКТ": 6,
    "ЗДОРОВА": 7,
    "КЕТОЗ": 8,
    "МАСТИТ": 9,
    "МЕТРИТ": 10,
    "НА_СХЕМУ": 11,
    "НЕОСЕМ": 12,
    "ОСЕМЕН": 13,
    "ОТЕЛ": 14,
    "ПАЛА": 15,
    "ПАРЕЗ": 16,
    "ПЕРЕВОД": 17,
    "ПОСЛЕД": 18,
    "ПРОДАНА": 19,
    "ПРОФОТ": 20,
    "РАСЧКОП": 21,
    "СО_СХЕМЫ": 22,
    "СТЕЛН": 23,
    "СТЕЛНДО": 24,
    "СУХ2": 25,
    "СУХОСТ": 26,
    "ХРОМОТА": 27,
    "ЯЛОВАЯ": 28,
    "ABORT": 1,
    "BRED": 13,
    "DNB": 12,
    "DRY": 26,
    "FOOTRIM": 21,
    "FRESH": 14,
    "ILLMISC": 2,
    "KETOS": 8,
    "LAME": 27,
    "MAST": 9,
    "METR": 10,
    "MOVE": 17,
    "NULSCM": 22,
    "OPEN": 28,
    "POT": 20,
    "RP": 18,
    "SOLD": 19,
    "TOSCM": 11,
    "WEIGHT": 5,
    "WELL": 7,
}

EVENTS_BY_CATEGORIES = {
    "БОЛЕЗНИ": [
        EVENTS["АБОРТ"],
        EVENTS["БОЛЕЗНЬ"],
        EVENTS["КЕТОЗ"],
        EVENTS["МАСТИТ"],
        EVENTS["МЕТРИТ"],
        EVENTS["ПАРЕЗ"],
        EVENTS["ПОСЛЕД"],
        EVENTS["ХРОМОТА"],
        EVENTS["ABORT"],
        EVENTS["ILLMISC"],
        EVENTS["KETOS"],
        EVENTS["LAME"],
        EVENTS["MAST"],
        EVENTS["METR"],
        EVENTS["RP"],
    ],
    "СТАНДАРТНЫЙ СОБЫТИЯ": [
        EVENTS["ВЕС"],
        EVENTS["ДЕФЕКТ"],
        EVENTS["ПЕРЕВОД"],
        EVENTS["СУХ2"],
        EVENTS["СУХОСТ"],
        EVENTS["DRY"],
        EVENTS["FOOTRIM"],
        EVENTS["MOVE"],
        EVENTS["WEIGHT"],
    ],
    "ИСХОД": [
        EVENTS["ЗДОРОВА"],
        EVENTS["ПАЛА"],
        EVENTS["ПРОДАНА"],
    ],
    "ВОСПРОИЗВОДСТВО": [
        EVENTS["НА_СХЕМУ"],
        EVENTS["НЕОСЕМ"],
        EVENTS["ОСЕМЕН"],
        EVENTS["ОТЕЛ"],
        EVENTS["СО_СХЕМЫ"],
        EVENTS["СТЕЛН"],
        EVENTS["СТЕЛНДО"],
        EVENTS["ЯЛОВАЯ"],
        EVENTS["BRED"],
        EVENTS["DNB"],
        EVENTS["FRESH"],
        EVENTS["NULSCM"],
        EVENTS["OPEN"],
        EVENTS["TOSCM"],
    ],
    "ПРОФИЛАКТИКА": [
        EVENTS["ПРОФОТ"],
        EVENTS["POT"],
        EVENTS["ВАКВИРУС"],
        EVENTS["ВАКЦИН"],
        EVENTS["РАСЧКОП"],
        EVENTS["FOOTRIM"],
    ],
}
